networks:
  public:
    external: true
services:
  backend:
    image: python:3.14.3-alpine
    container_name: photoful_backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - APP_HOST=your.domain.here
    command: sh -c "pip install -r requirements.txt && python app.py"
    networks:
      - public
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.photofulapi.rule: "Host(`your.domain.here`) && (PathPrefix(`/api`) || PathPrefix(`/uploads`) || PathPrefix(`/socket.io`))"
      traefik.http.routers.photofulapi.entryPoints: websecure
      traefik.http.routers.photofulapi.tls.certresolver: cloudflare
      traefik.http.services.photofulapi.loadbalancer.server.port: "5000"
      traefik.docker.network: public
  frontend:
    image: node:25.8.0-alpine
    container_name: photoful_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm ci && npm run build && npx serve dist -s -l 3000"
    depends_on:
      - backend
    networks:
      - public
    labels:
      traefik.enable: "true"
      traefik.http.routers.photoful.rule: "Host(`your.domain.here`)"
      traefik.http.routers.photoful.entryPoints: websecure
      traefik.http.routers.photoful.tls.certresolver: cloudflare
      traefik.http.services.photoful.loadbalancer.server.port: "3000"
      traefik.docker.network: public
